server:
  port: 8551
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    consul:
      host: http://127.0.0.1
      port: 8500
      discovery:
        serviceName: ${spring.application.name}    # 注册到consul的服务名称
    config:
      server:
        git:
          uri: https://github.com/mingmingzhixiao/polymerization.git       # 配置git仓库的地址
          search-paths: classpath:/polymerization/src/main/resources/repo/dev                          # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: mingmingzhixiao                                          # git仓库的账号
          password: Wu123456                                         # git仓库的密码
          force-pull: true
          default-label: master